version: '2'
services:
  server1.control:
    image: saneax/fedora
    hostname: control
    volumes:
      - ansible:/root/ansible
    ports:
      - "2224:22"
      - "8081:8080"

  server2.lb01:
    image: saneax/fedora
    hostname: lb01
    ports:
      - "2225:22"
      - "8082:80"

  server3.app01:
    image: saneax/fedora
    hostname: app01
    ports:
      - "2226:22"
      - "8083:8080"

  server3.app02:
    image: saneax/fedora
    hostname: app02
    ports:
      - "2227:22"
      - "8084:8080"

  server3.db01:
    image: saneax/fedora
    hostname: db01
    ports:
      - "2228:22"
      - "8085:8080"

volumes:
  ansible:


