---
- name: install packages into control machine
  hosts: control
  tasks:
    - name: install tools
      dnf: name={{item}} state=present update_cache=yes
      with_items:
        - curl
        - stress
      
